[package]
name = "lattice-sensor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lattice-domain = { path = "../lattice-domain" }
pnet_datalink.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis"] }

[dev-dependencies]
