[package]
name = "lattice-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
lattice-domain = { path = "../lattice-domain" }
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
